### ISSUE TITLE
ElasticSearch index is not populated

### ISSUE THREAD

**Issue by manelephant** [jorge07/symfony-4-es-cqrs-boilerplate#105]
Hi everyone,

Everything is working great except i have nothing in ElasticSearch.

Well no index is created. Isn't it supposed to create/populate the index when you post a new user ? (as defined in the workflow doc)

Sorry if i missed something in the doc...

Cheers

**Comment by jorge07** [comment]
Hi, thanks for report it. 

ES is populated async with this worker https://github.com/jorge07/symfony-4-es-cqrs-boilerplate/blob/master/docker-compose.yml#L25-L29

Can you provide this container logs?

**Comment by manelephant** [comment]
Thanks @jorge07 for pointing this out !

**Comment by jorge07** [comment]
You're very welcome!
