### ISSUE TITLE
No order property in entities

### ISSUE THREAD

**Issue by ferrius** [jorge07/symfony-4-es-cqrs-boilerplate#106]
Every entity (special with no sequence ids) should have created time or smth else to sort them in lists or collections.

**Comment by jorge07** [comment]
Yep. 100% agree with you. I did not add it as this entities are just examples. But totally needed for enterprise projects.

**Comment by jorge07** [comment]
I'm +1 for a PR

**Comment by warguns** [comment]
Just created a pull request for that. Please check: https://github.com/jorge07/symfony-4-es-cqrs-boilerplate/pull/110/files
