### ISSUE TITLE
Question about value objects

### ISSUE THREAD

**Issue by ferrius** [jorge07/symfony-4-es-cqrs-boilerplate#107]
IMHO value objects should carry more complex business logic than validation rules. Wrapping every scalar value in own class complicates simple things. The best way i think to use private setters with assertions inside.

**Comment by jorge07** [comment]
By doing this your aggregates will grow a lot. And your aggregate will need to deal with logic than can be encapsulated in a better way. It will also simplify your tests suite and allow you to reuse and also cast this object in another places.

Here for example: https://github.com/jorge07/symfony-4-es-cqrs-boilerplate/blob/master/src/Domain/User/Specification/UniqueEmailSpecificationInterface.php#L15

It will ensure you receive a valid email and not just an string. By doing this you guarantee consistency and symplify test suite.

**Comment by ferrius** [comment]
I understand, thank you

**Comment by jorge07** [comment]
You're very welcome
