### ISSUE TITLE
Building prod image

### ISSUE THREAD

**Issue by Lutacon** [jorge07/symfony-4-es-cqrs-boilerplate#11]
When I'm building the production image using `docker-compose -f docker-compose.prod.yml build`

I get the following error : 

```
!!  PHP Fatal error:  Uncaught Error: Class 'Symfony\Bundle\TwigBundle\TwigBundle' not found in /build/src/Kernel.php:34
.....
ERROR: Service 'php' failed to build: The command '/bin/sh -c composer run-script post-install-cmd' returned a non-zero code: 255
```

Did you have this issue?

**Comment by jorge07** [comment]
I look at composer.json and Twig is not set as dependency but in dev exist because is required by the profiler. Adding Twig as dependency should fix the issue.

**Comment by Lutacon** [comment]
Yes. That was the problem.  Now I have another one with the cache:warmup command but I'm gonna open a new issue. 

Btw I owe you a few beers :)

**Comment by jorge07** [comment]
The fix is now merged. Feel free to close if works
