### ISSUE TITLE
How to get started?

### ISSUE THREAD

**Issue by ThomasNunninger** [jorge07/symfony-4-es-cqrs-boilerplate#113]
This project looks very promising. But sorry, I feel a little bit lost. How to get this installed correctly as dependency?

I tried to install it via `composer`:

`composer.json`:
```
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/jorge07/symfony-4-es-cqrs-boilerplate"
        }
    ],
    "require": {
        "jorge07/symfony-4-es-cqrs-boilerplate": "dev-master"
    }
}
```

Install via Composer:

```
$ composer  install
Loading composer repositories with package information
Updating dependencies (including require-dev)                                       
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for jorge07/symfony-4-es-cqrs-boilerplate dev-master -> satisfiable by jorge07/symfony-4-es-cqrs-boilerplate[dev-master].
    - jorge07/symfony-4-es-cqrs-boilerplate dev-master requires symfony/lts ^4@dev -> satisfiable by symfony/lts[4.x-dev] but these conflict with your requirements or minimum-stability.
```

**Comment by Lutacon** [comment]
I don't think it's possible to install the project as a dependency. In the end this is an Symfony app.

Any reason to start it as a dependency?

**Comment by ThomasNunninger** [comment]
Thanks for the fast reply.
Do I understand correctly:
* I clone the repository,
* throw away `.git`, and
* clean up what I do not need?
If yes: Any hints which CI-related files are specifically for this project and which are meant for your project?
Are there any further examples?

**Comment by jorge07** [comment]
Hi @ThomasNunninger 

Yes, basically what we've in [here](https://github.com/jorge07/symfony-4-es-cqrs-boilerplate#project-setup) is the setup so:

- Clone repo
- Remove .git
- Remove `.travis.yaml` file is your using another ci tool
- Rename compose.json project name, repo, etc
- Start adding and removing stuff you don't need from the repo

If you see this useful, it may be worth it to add another entry in the makefile

**Comment by ThomasNunninger** [comment]
Thanks for your reply. I think that's what I was looking for.
