### ISSUE TITLE
New Messenger Component in Symfony 4.1 to implement CQRS

### ISSUE THREAD

**Issue by Kwadz** [jorge07/symfony-4-es-cqrs-boilerplate#124]
The article [CQRS is easy with Symfony 4 and his Messenger Component](https://stefanoalletti.wordpress.com/2018/08/10/cqrs-is-easy-with-symfony-4-and-his-messanger-component/) explains how to use the [new Messenger Component in Symfony 4.1](https://symfony.com/doc/current/components/messenger.html) to implements the CQRS pattern. 

What do you think about it? Do you think it could be a good idea to implement it in _symfony-4-es-cqrs-boilerplate_?

**Comment by jorge07** [comment]
@Lutacon was working on it in #73 but as the new component it is... Lot of breaking changes were added. But yes 100% something we want here

**Comment by jorge07** [comment]
related #132

**Comment by jorge07** [comment]
Very happy to close this as is resolved in #132
