### ISSUE TITLE
Command Handler: persisting data

### ISSUE THREAD

**Issue by Shyroby** [jorge07/symfony-4-es-cqrs-boilerplate#125]
How are data persisted in write database from command handler ?i'm a beginner with es-cqrs and it's difficult for me to understand this step!

**Comment by Lutacon** [comment]
The projectors are listening on events of the EventBus so when an event is published it listen to the events and store it in the write side.

It's better explained [here](https://github.com/jorge07/symfony-4-es-cqrs-boilerplate/blob/master/doc/GetStarted/Projections.md)

**Comment by Shyroby** [comment]
So, if i understand, the **UserEmailReadProjectionFactory**  class is used to persist data on the db, right?

**Comment by jorge07** [comment]
Right. It's a listener that will receive the events after they are persisted so you can do whatever you want with them.

**Comment by Shyroby** [comment]
Read class to Write data....it confuses me a little!

**Comment by jorge07** [comment]
Ops Typo
