### ISSUE TITLE
What are the specs of your PHP7.1 image

### ISSUE THREAD

**Issue by jonathangreco** [jorge07/symfony-4-es-cqrs-boilerplate#13]
Hi,

First of all great work, and really nice of you to share it.

I would like to know what the purpose  of this image `jorge07/alpine-php:7.1-dev-sf`.

Can we replace by one more generic ? Is your project work the same way ?
What we need to achieve to do so ?

Thanks again for your amazing work.

**Comment by jorge07** [comment]
Hi @jonathangreco and thanks.

The purpose of this image is provide tools for development and some aliases for symfony applications. And extends directly from the production ready image. See [here](https://github.com/jorge07/alpine-php/blob/master/doc/Schema.md)

This images are battle tested and I'm it in sites with billions of request per day. But, yes you can replace it by your own without problem or extend this images. The specs are in https://github.com/jorge07/alpine-php. 

Once you're done replace the images in the docker compose files are that's it.

**Comment by jonathangreco** [comment]
Thanks for the answer :)
