### ISSUE TITLE
Why 'make phpunit' delete database ?

### ISSUE THREAD

**Issue by jonathangreco** [jorge07/symfony-4-es-cqrs-boilerplate#15]
As the title expose the question :

```
.PHONY: phpunit
phpunit: db ## execute project unit tests
		docker-compose exec php sh -lc './bin/phpunit'
```
```
make phpunit
docker-compose exec php sh -lc './bin/phpunit'
#!/usr/bin/env php
stty: standard input
PHPUnit 6.5.6 by Sebastian Bergmann and contributors.

Testing Api Test Suite
.........................................                         41 / 41 (100%)

Time: 57.98 seconds, Memory: 22.00MB

OK (41 tests, 88 assertions)

Generating code coverage report in HTML format ... done

```
Why the database has to be deleted for running tests ? I tried to remove it, no errors showed up in the testsuite so I just need to understand if it's the best practice that I don't know, or something else.

**Comment by jorge07** [comment]
It's deleting the database to avoid race conditions and starts the test suite from a empty state

**Comment by jonathangreco** [comment]
Thanks like I said I'm new to all of those concept you've put into this boilerplate, my questions can be very basic.
