### ISSUE TITLE
User class | Interacting with more entities

### ISSUE THREAD

**Issue by abelardolg** [jorge07/symfony-4-es-cqrs-boilerplate#180]
Hi there,
I wonder if I could enrich this app by adding more entities such as project. 

For example, I would like to represent this ERD:
![Captura de pantalla de 2020-07-10 15-02-36](https://user-images.githubusercontent.com/22522883/87157364-745c4400-c2be-11ea-872c-2fd64c3b1653.png)

Let me know if you consider it a nice idea, please.

Best regards.

**Comment by jorge07** [comment]
This project it's just a template. You can create you own by just forking the repo.
Whenever we have a change in master you just need to rebase to keep your fork up to date. I think is out of the project scope.

**Comment by jorge07** [comment]
Thanks for the feedback
