### ISSUE TITLE
BIG THANKS!!!

### ISSUE THREAD

**Issue by abelardolg** [jorge07/symfony-4-es-cqrs-boilerplate#181]
Since Github doesn't show a tab to leave our feedback about this project, I would like to leave it here (not issue) to thank you have shared this project with us.

It allowed me to build a Symfony-5-es-cqrs based project to test my skills about this clean architecture. 

My next step is to build a real website with WHM panel and centOS 7. 

🏅🏅🏅🏅🏅 I will document this process to share with the global community. 

Big thanks, @jorge07  💪💪💪💪💪💪💪

**Comment by jorge07** [comment]
Thanks to you and all the people that contributed in one way or another. I've learnt a lot from all of you
