### ISSUE TITLE
Undockerized version

### ISSUE THREAD

**Issue by abelardolg** [jorge07/symfony-4-es-cqrs-boilerplate#182]
Hi there,

I am modifying your original project in order to run an undockerized version. I know you don't give any support to another version of this project, so I would thank to anybody any help about this issue:

My first stop is the broadway 'events' table. This table must be available before run the application since the app stores events inside of it:

1. I run ```composer install``` to recreate the vendor dir;
2. I googled to see when this table is automatically created. According to this [page](https://github.com/broadway/broadway-bundle/issues/40), I must run the following command:
``` bin/console broadway:event-store:schema:init ``` but this command is not available;

I don't know how this bundle works, but shouldn't it automatically create the table when Symfony runs at first time? 🤔

Again, this issue is not related to your project but any help would be welcome.

Best regards.

**Comment by jorge07** [comment]
Hi @abelardolg 

Broadway schema is included in doctrine migrations to keep things in one place only. See migrations directory https://github.com/jorge07/symfony-5-es-cqrs-boilerplate/blob/master/src/Infrastructure/Share/Migrations/Version20180102233829.php#L43

You can reproduce all of this outside docker by following makefile start steps.

I hope you find this helpful

**Comment by abelardolg** [comment]
Thanks for your prompt reply.

Best regards.

**Comment by jorge07** [comment]
Closing, feel free to reopen or open another issues for future questions
