### ISSUE TITLE
Migrations y Conexión Mysql server

### ISSUE THREAD

**Issue by bareser** [jorge07/symfony-4-es-cqrs-boilerplate#186]
Hola, tengo dos puntos los cuales no consigo resolver:

- **Conectarme a la BBDD:** estoy intentado conectarme a mysql utilizando 127.0.0.1, puerto 3306  usuario: root y pass:api pero no consigo acceder, siempre me da error: Connection error! connect ECONNREFUSED 127.0.0.1:3306
He probado con diferentes hosts: localhost, mysql, 127.0.0.1 etc pero sin éxito. ¿en que me estoy equivocando?
Tengo que decir que todos los contenedores están funcionado bien. 
Probando a crear usuarios desde el propio interface me todo funciona bien, asi que la BBDD está funcionando.

- **Migraciones**: no entiendo como poder crear mi propia migracion. Ejecutando make db se crea un archivo nuevo de migraciones pero vacío.
He creado una nueva entidad en el Domain, Application e Infraestructure y además he creado el archivo correspondiente en la carpeta: mapping\orm\domain y projections pero no sé que me falta o la forma de ir creando mis tablas en BBDD ¿las tengo que crear a mano?

Muchas gracias de antemano.
![connect - mysql](https://user-images.githubusercontent.com/24532285/89206253-54682980-d5b9-11ea-9e7b-8f88e9036b2b.png)

![xml orm](https://user-images.githubusercontent.com/24532285/89206362-7eb9e700-d5b9-11ea-8254-6e9a2b0e5f5f.png)

**Comment by jorge07** [comment]
Hey 

1- Puedes hacer un paste aquí del output de `docker ps`?

2- Las migrations se generan con Doctrine migrations. Yo suelo hacer `make s=php sh` y dentro del container `./bin/console doctrine:migrations:diff` luego de esto reviso el fichero que me crea y dado que la integración de broadway es bastante mala de momento borro a mano lo relativo a la table de event store.
Un saludo

**Comment by bareser** [comment]
Gracias @jorge07 
1.-
```
CONTAINER ID        IMAGE                                                 COMMAND                  CREATED             STATUS              PORTS                                                                                        NAMES
917d9cdeea0a        nginx:1.17-alpine                                     "nginx -g 'daemon of…"   23 hours ago        Up About a minute   0.0.0.0:80->80/tcp                                                                           erpcore_nginx_1
00a7d80d8562        jorge07/alpine-php:7.4.3-dev                          "/sbin/tini -- /app/…"   23 hours ago        Up About a minute   22/tcp, 9000/tcp                                                                             erpcore_workers_1
9069f5ae5b64        jorge07/alpine-php:7.4.3-dev                          "/sbin/tini -- super…"   23 hours ago        Up About a minute   9000/tcp, 0.0.0.0:2323->22/tcp                                                               erpcore_php_1
b4c09669b344        mysql:8.0                                             "docker-entrypoint.s…"   23 hours ago        Up 20 hours         0.0.0.0:3306->3306/tcp, 33060/tcp                                                            erpcore_mysql_1
e92f99a31279        rabbitmq:3-management                                 "docker-entrypoint.s…"   23 hours ago        Up 20 hours         4369/tcp, 5671/tcp, 0.0.0.0:5672->5672/tcp, 15671/tcp, 25672/tcp, 0.0.0.0:15672->15672/tcp   erpcore_rmq_1
36e476595191        docker.elastic.co/elasticsearch/elasticsearch:7.6.2   "/usr/local/bin/dock…"   23 hours ago        Up 20 hours         0.0.0.0:9200->9200/tcp, 9300/tcp                                                             erpcore_elasticsearch_1
ee7c5b54ac5e        docker.elastic.co/kibana/kibana:7.6.2                 "/usr/local/bin/dumb…"   2 weeks ago         Up About a minute   0.0.0.0:5601->5601/tcp                                                                       erpcore_kibana_1
```

2.- gracias por el consejo, lo voy a probar.

**Comment by jorge07** [comment]
@bareser necesito saber os, docker ip, etc... Ya que en mi lado no consigo reproducir el problema y tengo acceso a mysql sin ningun problema [attached]
![mysqlconn](https://i.imgur.com/1UeJy04.png)

**Comment by bareser** [comment]
Hola @jorge07  estoy utilizando windows con wsl2 con lo cual es como si estuviera en Linux (ubuntu más concretamente).
Para dar mas detalles del contenedor mysql he ejecutado el comando **docker inspect b4c09669b344** y te copio la parte de Networksettings por si está la información.

Gracias por tu ayuda.

"NetworkSettings": {
            "Bridge": "",
            "SandboxID": "d33a2b395312af1c1c1809b33bf6507309c9abad90d516fb662f43c00e5c083f",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "3306/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "3306"
                    }
                ],
                "33060/tcp": null
            },
            "SandboxKey": "/var/run/docker/netns/d33a2b395312",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "erpcore_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "b4c09669b344",
                        "mysql"
                    ],
                    "NetworkID": "65504454f9fd9782c262a11e1bedb912413192526a4fd3c4a1e9e3fa6a2c0148",
                    "EndpointID": "906d212c42a228bdc670d49b1e94133d9608b8f81f73e9f3b3a1eaa407ad276b",
                    "Gateway": "172.21.0.1",
                    "IPAddress": "172.21.0.3",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:15:00:03",
                    "DriverOpts": null
                }
            }
        }
    }

**Comment by bareser** [comment]
@jorge07 ya me funciona la conexion mysql
Cosas de la informática, he desistalado la extensión para vscode de mysql he cerrado todo he vuelto a instalar y me ha conectado a la primera 👍 
Muchas gracias por tu tiempo y disposición.

**Comment by jorge07** [comment]
Mi última experiencia con Windows se remonta a 2013, pero tengo un xps en casa, a ver si puedo montar una partición para probar
