### ISSUE TITLE
ex-soap - problems with installation

### ISSUE THREAD

**Issue by oskarbarcz** [jorge07/symfony-4-es-cqrs-boilerplate#203]
Hey jorge07,

I need to install ext-soap in order to install one of my dependencies. How do I do it with your image? Can you describe this in few words?

Thanks in advance,
Oskar Barcz

**Comment by jorge07** [comment]
Hi Oscar

You'll need to add `php7-soap` in the [Dockerfile](https://github.com/jorge07/symfony-5-es-cqrs-boilerplate/blob/symfony-5/etc/artifact/Dockerfile#L7) apk add step in the dev step and the prod one. This means that there's probably room for improvement in the Dockerfile to be a bit more DRY, will give it a thought.

**Comment by oskarbarcz** [comment]
Okey, but I'm kinda lost there - on regular server I'd use
`apt install php74-soap`,
and what exactly I'm supposed to do here?

**Comment by jorge07** [comment]
It's an alpine OS and uses apk as package manger. You can find base image and OS version [here](https://github.com/jorge07/alpine-php/blob/master/7.4/Dockerfile#L1) and search for the official packages you need [here](https://pkgs.alpinelinux.org/packages?name=php*&branch=v3.10). Codecast repository is included in base image so you can install packages [from there](https://dl.bintray.com/php-alpine/v3.10/php-7.4/x86_64/) by simply adding `@cast` at the end of the package name.
Example: `RUN apk add php7-soap@cast`

**Comment by oskarbarcz** [comment]
Now it's clear, thanks a lot for your work - I didn't expected such fast response!

**Comment by jorge07** [comment]
Added this PR as reference #204 so other people ca benefit too.
