### ISSUE TITLE
type mismatch when adding new field

### ISSUE THREAD

**Issue by dodgyprincess** [jorge07/symfony-4-es-cqrs-boilerplate#21]
I was learning more about CQRS and when learning added a name field and a NameChangeCommand, I can create a user with a name but using the CLI command we get the following error, if you could provide some insight as to why or when this is happening i would be very grateful. If you require any further information I can provide the files i have edited

In ReflectionEmbeddedProperty.php line 81:

  Warning: ReflectionProperty::getValue() expects parameter 1 to be object, string given

**Comment by dodgyprincess** [comment]
We have added a __toString() i can provide a link to my repo with my changes on if that would help?

https://github.com/dodgyprincess/cqrs-practice

**Comment by jorge07** [comment]
@dodgyprincess I downloaded you repo and did some tests. This are my results: https://github.com/dodgyprincess/cqrs-practice/commit/1a3a0671ba166233c29b0a9820dd0237dc75cc7c#r29179818

**Comment by jorge07** [comment]
I'll close it as is not directly related with the repo ;)
