### ISSUE TITLE
Wrong namespace for App\Domain\User\Query ?!

### ISSUE THREAD

**Issue by tonivdv** [jorge07/symfony-4-es-cqrs-boilerplate#22]
Hi @jorge07 ,

First of all many thanks for taking the time to demonstrate a DDD-es-cqrs example with sf4. I use it to start up a new project, and doing ddd for some time but not sf4, it does help a lot.

However, I'm a bit sceptical about the location of the classes in App\Domain\User\Query ... Imho they should not be in the Domain namespace. Generally what we will get for the "Query" part are projections and only data necessary for views, right?!

I guess the Read repository interface is acceptable to keep in the Domain layer, but the UserView class seems not right to me ...

What's your thought on this?

Thanks

**Comment by jorge07** [comment]
Well, it's true, the repo it's not perfect and have some misconceptions like this.

Let's move it to the infrastructure layer, where it should be since the beginning.
