### ISSUE TITLE
why have you store two times the events?

### ISSUE THREAD

**Issue by yoelotero** [jorge07/symfony-4-es-cqrs-boilerplate#5]
Broadway manage the event store on MYSQL but I am seeing  you have a AsyncEventPublisher that publish the event in elasticSearch to.

**Comment by jorge07** [comment]
I'm using Elasticsearch as reporting tool to have pseudo real time stats.

The point it's that when Mysql should be always a consistent event store, in Elasticsearch this consistency will occur eventually.

**Comment by jorge07** [comment]
Note that `AsyncEventPublisher` is publishing the events in rabbitmq not send it it to Elasticsearch. The point it's use rabbitmq to communicate between microservices or execute async tasks like cook data for BI

**Comment by yoelotero** [comment]
Cool! thanks for the repo! It is very util!
