### ISSUE TITLE
Stateless API authentication

### ISSUE THREAD

**Issue by pascal08** [jorge07/symfony-4-es-cqrs-boilerplate#61]
I think API authentication is a really nice feature to have included in this boilerplate.

This is what I had in mind:

- A new endpoint for authentication
- The endpoint returns a token that can be used for successive requests requiring the user to be authenticated

Regarding some people a command bus should not return a value in CQRS context. I think it would be complicated to return the token to the user without returning it directly from the command handler. This would be a worth a discussion I guess.

If we make use of, for example: [LexikJWTAuthenticationBundle](https://github.com/lexik/LexikJWTAuthenticationBundle/blob/master/Resources/doc/index.md#prerequisites), then we need to create an abstraction to be able to create token using the User aggregate root (this bundle requires us to pass Symfony\Component\Security\Core\User\UserInterface).

I would like to hear your opinions about this.

**Comment by jorge07** [comment]
@pascal08 agree with you. Have a look at #62 and give me your thoughts please.
