### ISSUE TITLE
Event-replay, snapshotting, etc?

### ISSUE THREAD

**Issue by pascal08** [jorge07/symfony-4-es-cqrs-boilerplate#69]
So far I think this repository is a great resource for developers new to CQRS/ES/DDD. I don't know you had a certain intention when you created this repository, but personally I think it would be awesome if we add features like event-replay, snapshotting and maybe even a microservice architecture example connected using RabbitMQ (or maybe Kafka). 

If you agree with me I'd be glad to assist implementing some of these features. What do you think?

**Comment by jorge07** [comment]
+1 for event replay
Broadway has a poor snapshot implementation.
Happy to do some king of pub/sub demo too.

PRs are welcome but I'll try to find some time to implement this things.

**Comment by pascal08** [comment]
Great! If you'd like I could implement the event-replay functionality. I was thinking about a simple CLI command to trigger an event-replay. In the beginning it will only support event filtering (when you replay the event log it will only replay the events you're interested in). Later on we could add some more advanced features like debugging etc. What do you think?
