### ISSUE TITLE
Question: Why not replace Controllers by Actions ?

### ISSUE THREAD

**Issue by karael** [jorge07/symfony-4-es-cqrs-boilerplate#79]
Hi,

First of all thanks for this repository, it's a great boilerplate implementing CQRS 👍 

I have a question about the UI especialy Controllers. I think CQRS is compatible with ADR pattern am I wrong ?
Here for exemple we could replace Controllers by Action and Response could manage the way we want to respond json, html ...

What do you think about it ?

**Comment by jorge07** [comment]
Yes, you can. It depend of the purpose. In this repo, the rest api and the website are different use cases.

Do you know how the ADR implementation could modify the current structure in UI considering this?

**Comment by karael** [comment]
both could be used we could choice what kind of responder we want to use for exemple in config or better in http header.
They are differents way to implement this.
If you want to keep UI, just remove Web and Rest then replace them by action and responder.
 My favourite structure is
src
|-framework
..|-action
..|-command (symfony)
..|-responder
