### ISSUE TITLE
Table for events its not defined anywhere

### ISSUE THREAD

**Issue by Lutacon** [jorge07/symfony-4-es-cqrs-boilerplate#8]
I don't find where is the table for events defined. Also if I create a new doctrine migration automatically wants to remove this table. Is this normal?

**Comment by Lutacon** [comment]
Nevermind. I just found it. It's in a migration file.

https://github.com/jorge07/symfony-4-es-cqrs-boilerplate/blob/master/src/Infrastructure/Share/Migrations/Version20180102233829.php#L20-L25

**Comment by jorge07** [comment]
Yes, that's the case. I'm using Broadway event store dbal for that purpose. It's not best way to handle it as the schema may change in future releases but if easy to change if needed.
