### ISSUE TITLE
Related objects

### ISSUE THREAD

**Issue by djkoza** [jorge07/symfony-4-es-cqrs-boilerplate#89]
Hi,
I have some problems with save and fetch object with related field, but some example:
1) User
2) Stream

Stream has owner User, so mapping:

stream
```
    <entity name="App\Infrastructure\Stream\Query\Projections\StreamView" table="streams">
        <id name="uuid" type="uuid_binary" column="uuid"/>
        (...)
        <many-to-one field="user" target-entity="App\Infrastructure\User\Query\Projections\UserView" inversed-by="streams">
            <join-column nullable="false" referenced-column-name="uuid" />
        </many-to-one>
    </entity>
```

user
```
    <entity name="App\Infrastructure\User\Query\Projections\UserView" table="users">
        <id name="uuid" type="uuid_binary" column="uuid"/>
        (...)
        <one-to-many field="streams" target-entity="App\Infrastructure\Stream\Query\Projections\StreamView" mapped-by="user">
        </one-to-many>
    </entity>
```

I want to create new stream, related to User. So, I create CreateStreamCommand and Handler, like this:

```
    public function __invoke(CreateStreamCommand $command): void
    {
        $stream = $this->streamFactory->register($command->uuid, $command->user, $command->parameters);

        $this->streamRepository->store($stream);
    }

    public function __construct(StreamFactory $streamFactory, StreamRepositoryInterface $streamRepository)
    {
        $this->streamFactory    = $streamFactory;
        $this->streamRepository = $streamRepository;
    }
```

register method from StreamFactory
```
    public function register(UuidInterface $uuid, UserViewInterface $user, Parameters $parameters): Stream
    {
        return Stream::create($uuid, $user, $parameters);
    }
```
create method from Stream
```
    public static function create(UuidInterface $uuid, UserViewInterface $user, Parameters $parameters): self
    {
        $stream = new self();

        $stream->apply(new StreamWasCreated($uuid, $user, $parameters));

        return $stream;
    }
```

And StreamWasCreated Event
```
    public function __construct(UuidInterface $uuid, UserViewInterface $user, Parameters $parameters)
    {
        $this->uuid         = $uuid;
        $this->user         = $user;
        $this->parameters   = $parameters;
    }

    /**
     * @throws \Assert\AssertionFailedException
     */
    public static function deserialize(array $data): self
    {
        Assertion::keyExists($data, 'uuid');
        Assertion::keyExists($data, 'user');
        Assertion::keyExists($data, 'parameters');

        return new self(
            Uuid::fromString($data['uuid']),
            $data['user'],
            Parameters::fromArray($data['parameters'])
        );
    }

    public function serialize(): array
    {
        return [
            'uuid'          => $this->uuid->toString(),
            'user'          => $this->user,
            'parameters'    => $this->parameters->toArray()
        ];
    }

```

At this step I don't serialize user, and everything is fine. But... When I want to get this Stream record, I see error: 
```
PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\FatalThrowableError: Argument 2 passed to App\Domain\Stream\Event\StreamWasCreated::__construct() must implement interface App\Domain\User\Query\Projections\UserViewInterface, array given, called in /app/src/Domain/Stream/Event/StreamWasCreated.php on line 51 in /app/src/Domain/Stream/Event/StreamWasCreated.php:32
Stack trace:
#0 /app/src/Domain/Stream/Event/StreamWasCreated.php(51): App\Domain\Stream\Event\StreamWasCreated->__construct(Object(Ramsey\Uuid\Uuid), Array, Object(App\Domain\Stream\ValueObject\Parameters))
#1 /app/vendor/broadway/broadway/src/Broadway/Serializer/SimpleInterfaceSerializer.php(58): App\Domain\Stream\Event\StreamWasCreated::deserialize(Array)
#2 /app/vendor/broadway/event-store-dbal/src/DBALEventStore.php(234): Broadway\Serializer\SimpleInterfaceSerializer->deserialize(Array)
#3 /app/vendor/broadway/event-store-dbal/src/DBALEventStore.php(93): Broadway\EventStore\Dbal\DBALEventStore->deserializeEvent(Array)
#4 /app/vendor/broadway/broadway/s in /app/src/Domain/Stream/Event/StreamWasCreated.php on line 32
```

I checked second argument, and it is empty array. So I think, problem is in unserialize event data.

So my second try was serialize User object, but then I can't save Stream object, because doctrine thinks user is new object and try to cascade persist.

What is the propper way to work with relationship?

Sorry my english ;)

**Comment by jorge07** [comment]
Hi @djkoza 

Your StreamWasCreated event is passing an array as Object. You need to deserialise User before pass it to the constructor. 
```
  /**
     * @throws \Assert\AssertionFailedException
     */
    public static function deserialize(array $data): self
    {
        Assertion::keyExists($data, 'uuid');
        Assertion::keyExists($data, 'user');
        Assertion::keyExists($data, 'parameters');

        return new self(
            Uuid::fromString($data['uuid']),
-          $data['user'],
+          User:: deserialize($data['user']),
            Parameters::fromArray($data['parameters'])
        );
    }
```

Also, I do not recommend use Projections in DomainEvents. A Projection is just a representation of the model, not the model itself. Use a domain object instead.

**Comment by djkoza** [comment]
Thanks a lot for your reply @blixit @jorge07 

> 
> you need to deserialize `$data['user'] `. it's an array.
> 

When I call CreateStreamCommand this is UserView object. But when I call (after save) to fetch

`$stream = $this->streamRepository->get($command->uuid);`

Then I get mentioned error and in this moment `$data['user']` it's an array - empty.

When I serialize with UserView::serialize()

```
        return [
            'uuid'        => $this->getId(),
            'credentials' => [
                'email' => (string) $this->credentials->email,
            ],
        ];
```

I have got error from doctrine about cascade persisting UserView. So, as I mentioned
> So my second try was serialize User object, but then I can't save Stream object, because doctrine thinks user is new object and try to cascade persist.

@blixit 
> I will advice you to use Id/Uuid instead of UserviewInterface and add other user informations when running a projection into the read model.

I tried this solution, but where is the best place code to fetch User from repository and assign them to Stream on create or update record? This must have happened before persist, because
> doctrine thinks user is new object and try to cascade persist.

@jorge07 
> Also, I do not recommend use Projections in DomainEvents. A Projection is just a representation of the model, not the model itself. Use a domain object instead.

if I understand correctly, my relation is needed to rebuild: "target-entity" not point to Projections, but to Domain objects?

Newbie questions, I'm new in DDD

Thanks a lot ;)

**Comment by jorge07** [comment]
I'll create a branch with a similar use case will be easier for others to look at this and see how to start or process with things like that.

**Comment by djkoza** [comment]
@jorge07 that will be very helpfull, I will be patient.
@blixit ok, thats fine - but's what with doctrine problem? I can't persist and flush Stream object because related User object is trying to persist too. As we know, User already exist and database fail to execute this insert (create) or update command.

**Comment by blixit** [comment]
>related User object is trying to persist too
this is a known issue with doctrine. you need to properly set your 'cascade' properties (on persist, on update, ...).
it's not due to es-cqrs

**Comment by djkoza** [comment]
@blixit I found some solutions,
1) merge() via entity manager
2) fetch User (related object) from orm and call setUser on Stream object
3) use JMSSerializerBundle and Doctrine object constructor

What is the best way to deal with this problem?

**Comment by blixit** [comment]
i use to use the 2nd solution and the 1st one in this order.

**Comment by djkoza** [comment]
@blixit ok, but some question - how can I get repository in StreamWasCreated event or in StreamView Projection?
We don't call this classes via service, so dependency injection dosent work. How to deal with that? I want to fetch related object in deserialize operation

**Comment by blixit** [comment]
>How can I get repository in StreamWasCreated event or in StreamView Projection
I think it's a bad design. (Maybe you mean the event handler.)

I think the goal of the :
- **projection** class  should be to store data between the **view** and the **storage** (projection)
-  **event** class  should be to store data between the **aggregate** and an **handler** (event handler, projector or any class subscribed to this event)

You should not call repository at this place.
I suggest you to fetch related objects from the commandhandler. For instance:
- in CreateStreamCommandHandler, you fetch a UserView and `$command->setUser($relatedUser)`
- ... call your aggregate register method `::register(..., $command->getUser(), ...)` 
- in your aggregate you can then create your event `StreamWasCreated(.., $userView, ...)`

**Comment by jorge07** [comment]
Hi @blixit @djkoza, 

I made this [branch](https://github.com/jorge07/symfony-4-es-cqrs-boilerplate/tree/example-relations) with an example of user relations and a way to minimise the couple between bounded contexts.

**Comment by jorge07** [comment]
Here the commit [reference](https://github.com/jorge07/symfony-4-es-cqrs-boilerplate/commit/1348e8366ca0cdd5e2a30792175dc7d13ec84f97)

**Comment by jorge07** [comment]
I think we can close it. Feel free to reopen it if needed it.
