### ISSUE TITLE
Async event publisher not called

### ISSUE THREAD

**Issue by Lutacon** [jorge07/symfony-4-es-cqrs-boilerplate#9]
I've been struggling with the AsyncEventPublisher and events been publish to RabbitMQ. 

For example, I create a new user. A new event would be sent to RabbitMQ and then to Elasticsearch.
The user is created perfectly, the event stored in Mysql table but the event is not sent to Rabbit.

Looking at the symfony profiler I'm seeing that the AsyncEventPublisher is not called on kernel.terminate. 

![image](https://user-images.githubusercontent.com/2017676/38783593-4e95dcd8-4104-11e8-80f5-0a35c517bac9.png)

Did you have that problem?

Thank you for your work & time !

**Comment by jorge07** [comment]
Strange...
I need the following information to debug that. 

1 - A screenshot of the rabbitmq admin of the exchange and the graphic of packages received.
2 - Be sure that you have the workers running BEFORE do any operation. The reason is that the consumers command also perform the configuration of the exchange and queues in rabbitmq.

**Comment by jorge07** [comment]
Tests are passing? There's a test covering that the publisher is called after kernel terminate event... False positive?

**Comment by jorge07** [comment]
It should be called otherwise this test will not pass https://github.com/jorge07/symfony-4-es-cqrs-boilerplate/blob/master/tests/Application/Query/User/FindByEmail/FindByEmailHandlerTest.php#L26

**Comment by Lutacon** [comment]
Yes. The strange is all the tests are passing.

I was testing more and I was able to send some events to RabbitMQ and consequently to elasticsearch. I was able to send UserSignIn and UserSignUp both for the UI. 

I'm not able to create a user form cli and the event sent to RabbitMQ.

![image](https://user-images.githubusercontent.com/2017676/38783755-ec72051a-4106-11e8-963c-f1d456d6e8a7.png)
![image](https://user-images.githubusercontent.com/2017676/38783775-5c83ee04-4107-11e8-804a-9721361badb5.png)

I just stop and up the containers to try again only from the cli but it's not working

**Comment by jorge07** [comment]
Looks like the Subscriber it's not subscribed to ConsoleEvents::TERMINATE.

**Comment by jorge07** [comment]
Append this event to https://github.com/jorge07/symfony-4-es-cqrs-boilerplate/blob/master/src/Infrastructure/Share/Event/Publisher/AsyncEventPublisher.php#L36 and it should work. I've the laptop at the office, so I'll prepare a pr tomorrow for this a cover it better in tests.

Thanks for your contribution!

**Comment by Lutacon** [comment]
Ouch >_<  Didn't think about that. I was debugging the kernel terminate.

Thank you for helping me out.
