### ISSUE TITLE
Upgrade to php 7.3

### ISSUE THREAD

**Issue by jorge07** [jorge07/symfony-4-es-cqrs-boilerplate#90]

**Comment by blixit** [comment]
What is the task ? I looking for a good first issue

**Comment by jorge07** [comment]
Basically edit docker files to make tests work with 7.3 and remove depreciation notices if exists

**Comment by jorge07** [comment]
We'll need to wait until xdebug 2.70 release. Current RCs has serious issues that cause segmentation faults 🎉

**Comment by kowalk** [comment]
@jorge07 it's done in https://github.com/jorge07/symfony-4-es-cqrs-boilerplate/pull/112

**Comment by jorge07** [comment]
https://github.com/symfony/symfony/pull/29349/files related?
