### ISSUE TITLE
Question: why not update read models asynchronously?

### ISSUE THREAD

**Issue by pascal08** [jorge07/symfony-4-es-cqrs-boilerplate#91]
For example, when we want to keep our read models in a different data storage than MySQL, we maybe want to update our read model outside of the request cycle that triggers the domain event(s). I might be incorrect but I think this is ultimately how CQRS should be implemented. What do you think?

**Comment by blixit** [comment]
Yeah I agree. I saw some implementations and it sounds common to write asynchronously to read models. use of message brokers can be relevant.

**Comment by pascal08** [comment]
Since our event store is the single source of truth, we don't need our models to be updated right away. If something fails in the asynchronous process, we can rebuild the read model. The guys behind Broadway wrote an article about this: http://labs.qandidate.com/blog/2015/10/07/asynchronous-event-processing-with-broadway-using-rabbitmq/.

**Comment by jorge07** [comment]
As in 90% of the time... "It depends" 

For scalability 100% async is the best way
For consistency... sync is easier.

Is up to you to balance and decide how it matches with your use cases.
