### ISSUE TITLE
Remove "abandoned" dependency: Symfony/LTS

### ISSUE THREAD

**Issue by zerai** [jorge07/symfony-4-es-cqrs-boilerplate#93]
Both branch (master/symfony-4.2-upgrade) have that package

From symfony/LTS repository:

Use symfony/flex instead and configure its extra.symfony.require setting to the version range you'd like to have.
For example, composer config extra.symfony.require "~4.1.0" restricts the versions of all Symfony components to ~4.1.0.

**Comment by jorge07** [comment]
Thanks @zerai for report this! Will do as part of #88

**Comment by jorge07** [comment]
Done! Thanks for report this 👌
