### ISSUE TITLE
Unique email validation

### ISSUE THREAD

**Issue by ferrius** [jorge07/symfony-4-es-cqrs-boilerplate#96]
First of all, thank you for a great example!

We have an aggregate domain rule "user must have an unique email", but we have just one assertion in factory. This is not a defensive way. In DDD domain object is permanently valid and can be used in stand alone manner. You can use specification pattern for validating aggregate rules.

```php
public function changeEmail(Email $email, UniqueEmailSpecification $uniqueEmailSpecification): void
{
        Assertion::notEq((string)$this->email, (string)$email, 'New email should be different');

	if (!$uniqueEmailSpecification->isSatisfiedBy($email)) {
		throw new EmailAlreadyExistException('Email already registered.');
	}

    $this->apply(new UserEmailChanged($this->uuid, $email));
}
```
The same in User::create

**Comment by jorge07** [comment]
Hi @ferrius 

In SignUp we handle this by `UserFactory` doing this:
```php
class UserFactory
{
    public function register(UuidInterface $uuid, Credentials $credentials): User
    {
        if ($this->userCollection->existsEmail($credentials->email)) {
            throw new EmailAlreadyExistException('Email already registered.');
        }

        return User::create($uuid, $credentials);
    }
```

The specification pattern can help also with this removing some code and being more DRY. Good catch 👍

**Comment by zerai** [comment]
Hi,
I think a domain service (interface + implementation) is better for this type of 'domain rule', not all domain rules must be aggregates invariant.
Check uniqueness requirement inside aggregate is not a good idea in this case. 
Maybe this article can clarify a little bit the difference.
[Email uniqueness as an aggregate invariant](https://enterprisecraftsmanship.com/2016/09/22/email-uniqueness-as-an-aggregate-invariant/)

**Comment by ferrius** [comment]
Thank you for the article.
But see the [next article](https://enterprisecraftsmanship.com/2016/10/05/how-to-know-if-your-domain-model-is-properly-isolated/) of this author and especially discussion in the comments.

**Comment by jorge07** [comment]
I think the point here is that it's needed in more than one place so the UserFactory is taking this responsibility and as soon as this is needed in other places, it gets invalidated. It can also be validated in the application layer (command handler) but I prefer be as close as possible to the domain layer

**Comment by jorge07** [comment]
Feedback appreciated here #99 ;)
